### PR TITLE
Light DQM generic application

### PR DESCRIPTION
**Pull request by mexanick**
The application aiming to run over the GEM data file (*.dat) and produce ROOT TTree and ROOT file with histograms added. It produces the basic distributions as well as CRC and various occupancy plots. 
Usage:
first, compile the event lib:
under gem-light-dqm/gemtreewriter/ run 
make all
under gem-light-dqm/dqm-root/ run 
make rundqm
The executable will be created under gem-light-dqm/dqm-root/bin/${XDAQ_OS}/${XDAQ_PLATFORM}/

launch it, supplying input file:
gem-light-dqm/dqm-root/bin/${XDAQ_OS}/${XDAQ_PLATFORM}/rundqm test_input.dat > test_input.log

It will produce three files:
* file with TTree: test_input.raw.root
* file with histograms: test_input.analyzed.root
* log file: test_input.log

If you want to remove the debug outputs in the log file you can set #define DEBUG 0 in following files:
gem-light-dqm/gemtreewriter/src/common/gemTreeWriter.cxx
and gem-light-dqm/dqm-root/src/common/treeReader.cxx

### CODE REVIEW

**Comment by jsturdy** [comment]
I tried to build the dqm-light-code (after merging central develop branch) and failed:
Seems to be missing an include definition in the gemtreewriter Makefile:
/tmp/sturdy/testing-releases/central-test/gem-light-dqm/gemtreewriter/../../gem-light-dqm/gemtreewriter/src/common/treeReaderExample.cxx:38:23: error: plotter.cxx: No such file or directory

And an outdated definition of this file (name changed to remove typo)
/tmp/sturdy/testing-releases/central-test/gem-light-dqm/gemtreewriter/../../gem-light-dqm/gemtreewriter/src/common/treeReaderExample.cxx:39:40: error: gem/readout/GEMslotContens.h: No such file or directory

These are all related to the missing plotter.cxx:
/tmp/sturdy/testing-releases/central-test/gem-light-dqm/gemtreewriter/../../gem-light-dqm/gemtreewriter/src/common/treeReaderExample.cxx: In function ‘int main(int, char**)’:
/tmp/sturdy/testing-releases/central-test/gem-light-dqm/gemtreewriter/../../gem-light-dqm/gemtreewriter/src/common/treeReaderExample.cxx:454: error: ‘setTitles’ was not declared in this scope
/tmp/sturdy/testing-releases/central-test/gem-light-dqm/gemtreewriter/../../gem-light-dqm/gemtreewriter/src/common/treeReaderExample.cxx:488: error: ‘getStyle’ was not declared in this scope
/tmp/sturdy/testing-releases/central-test/gem-light-dqm/gemtreewriter/../../gem-light-dqm/gemtreewriter/src/common/treeReaderExample.cxx:491: error: ‘printHistograms’ was not declared in this scope

**Comment by mexanick** [comment]
Hi Jared,

sorry, this is my fault. Too many location I had to change while merging and this one failed. I can foresee three solutions:
1). We actually can remove completely the treeReaderExample.cxx (I re-wrote it as  class in treeReader.cxx) 
2). For the moment you can just comment the lines 
$(CC) $(ADDFLAGS) $(ROOTLIBS) $($ROOTGLIBS) $(INC) $(SRC)/treeReaderExample.cxx $(LIB)/libEvent.so -o $(BIN)/reader
and
reader:
	$(CC) $(ADDFLAGS) $(ROOTLIBS) $($ROOTGLIBS) $(INC) $(SRC)/treeReaderExample.cxx $(LIB)/libEvent.so -o $(BIN)/reader

in the Makefile
3). Put correct path to headers (the plotter.cxx is under dqm-root/src/common you can add to the include path and gem/readout/GEMslotContents.h, actually here the typo was made when I created the file, and then Sergey renamed it, so I changed the name but not everywhere)

Sorry again for the inconvenience,

Misha
